version: 2
updates:
  - package-ecosystem: 'pip'
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: chore
    groups:
      pip-dependencies:
        patterns:
          - '*'

  - package-ecosystem: 'npm'
    directories:
      - '**/*'
    schedule:
      interval: 'weekly'
    commit-message:
      prefix: chore
    groups:
      npm-dependencies:
        patterns:
          - '*'
